version: '3.9'
services:
  manager:
    image: docker:19.03.12-dind
    privileged: true
    ports:
      - "12377:2377" # puerto de Docker Swarm
      - "8081:8081" # puerto del servicio unconnect_auth_ms
      - "81:81"    
      - "8000:8000" 
    environment:
      DOCKER_TLS_CERTDIR: ""
    command: dockerd --swarm-default-advertise-addr=eth0

  worker1:
    image: docker:19.03.12-dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    command: dockerd

  worker2:
    image: docker:19.03.12-dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    command: dockerd
