version: '3.9'
services:
  unconnect_mq:
    image: 'rabbitmq:3-management'
    container_name: 'unconnect_mq'
    ports:
      - '5672:5672'
      - '15672:15672'

  unconnect_posts_ms:
    container_name: 'unconnect_posts_ms'
    build:
      context: ./post_ms/
    # ports:
    #   - ${SERVER_PORT}:${SERVER_PORT}
    #   - 3021:3021
    command: npm run start:debug
    env_file: ./post_ms/.env
    depends_on:
      - unconnect_posts_db
    links:
      - unconnect_posts_db

  unconnect_posts_db:
    image: mongo:latest
    container_name: 'unconnect_posts_db'
    volumes:
      - mongodb_data_container:/data/db
    env_file:
      - .env
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}

  unconnect_media_ms:
    container_name: 'unconnect_media_ms'
    build:
      context: ./media_ms/
    volumes:
      - ./media_ms/uploads:/usr/src/media_ms/uploads
    # ports:
    #   - ${SERVER_PORT_MEDIA}:${SERVER_PORT_MEDIA}
    #   - 3022:3022
    command: npm run start:debug
    env_file:
      - .env
    depends_on:
      - unconnect_media_db
    links:
      - unconnect_media_db

  unconnect_media_db:
    image: mongo:latest
    container_name: 'unconnect_media_db'
    volumes:
      - mongodb_data_container_media:/data/db
    env_file:
      - .env
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE_MEDIA}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME_MEDIA}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD_MEDIA}
    ports:
      - 27018:27017

  unconnect_auth_ms:
    container_name: unconnect_auth_ms
    image: unconnect_auth_ms_image
    build:
      context: ./auth_ms/auth-service/
    # ports:
    #   - 8081:8081
    environment:
      - SPRING_PROFILE = ${SPRING_PROFILE}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - SPRING_RABBITMQ_HOST=unconnect_mq
    depends_on:
      - unconnect_auth_db
      - unconnect_mq
    links:
      - unconnect_auth_db
    restart: on-failure

  unconnect_auth_db:
    container_name: unconnect_auth_db
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - mysql_data_container_auth:/var/lib/mysq

  unconnect_group_ms:
    container_name: 'unconnect_group_ms'
    build:
      context: ./group_ms/
    ports:
      - 8001:8001
    volumes:
      - ./group_ms/db.sqlite3:/app/db.sqlite3
    environment:
      - DJANGO_SETTINGS_MODULE=group_ms.settings
      - PYTHONUNBUFFERED=1
    command: python manage.py runserver 0.0.0.0:8001

  unconnect_users_ms:
    container_name: 'unconnect_users_ms'
    build:
      context: ./user_ms/
    # ports:
    #   - 3003:3003
    command: ['/bin/bash', '-c', 'sleep 60 && npm start'] ## para que cargue la cola de mensajes.
    environment:
      - RABBITMQ_HOST=unconnect_mq
      - RABBITMQ_PORT=5672
    depends_on:
      - unconnect_auth_ms
      - unconnect_users_db
      - unconnect_mq

  unconnect_users_db:
    image: postgres:latest
    container_name: 'unconnect_users_db'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: usersdb
    ports:
      - '5432:5432'

  unconnect_notification_ms:
    container_name: 'unconnect_notification_ms'
    build:
      context: ./notification_ms/
    # ports:
    #   - 8080:8080
    command: ./main
    env_file:
      - environment.env

  unconnect_ag:
    container_name: unconnect_ag
    build:
      context: ./api_gateway/
    ports:
      - 8000:8000
    environment:
      PORT: 8000
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    links:
      - unconnect_users_ms
      - unconnect_group_ms
      - unconnect_posts_ms
      - unconnect_media_ms
      - unconnect_auth_ms
      - unconnect_notification_ms
volumes:
  mongodb_data_container:
  mongodb_data_container_media:
  mysql_data_container_auth:
  postgres_data:
