spring:
  cloud:
    config:
      enabled: true
      uri: http://localhost:8081
  datasource:
    url: jdbc:mysql://localhost:3306/authdb
    username: root
    password: newpass123
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  ldap:
    urls: ldap://localhost:389
    base: dc=unconnect,dc=com
    username: cn=admin,dc=unconnect,dc=com
    password: admin