# Generated by Django 5.0.3 on 2024-03-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='admins',
            field=models.ManyToManyField(related_name='administradores', to='groups.persons'),
        ),
        migrations.AddField(
            model_name='groups',
            name='members',
            field=models.ManyToManyField(related_name='miembros', to='groups.persons'),
        ),
        migrations.AddField(
            model_name='groups',
            name='owner_id',
            field=models.CharField(default=2002, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groups',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='persons',
            name='group_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
