# Generated by Django 5.0.3 on 2024-03-09 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_groups_admins_groups_members_groups_owner_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persons',
            name='group_id',
        ),
        migrations.AlterField(
            model_name='groups',
            name='owner_id',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
