# Generated by Django 5.0.3 on 2024-03-10 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_remove_persons_group_id_alter_groups_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='owner_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='groups.persons'),
        ),
    ]
