# Generated by Django 5.0.3 on 2024-03-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_groups_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='is_private',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
