# Generated by Django 5.0.3 on 2024-03-10 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_groups_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.persons'),
        ),
    ]
