# Generated by Django 5.0.3 on 2024-03-11 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_alter_groups_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='in_requests',
            field=models.ManyToManyField(related_name='solicitudes', to='groups.persons'),
        ),
    ]
