# Generated by Django 5.0.3 on 2024-03-11 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_groups_in_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='photo',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
