FROM eclipse-temurin:17

WORKDIR /app

ENV SPRING_PROFILE=docker

COPY target/auth-service-0.0.1-SNAPSHOT.jar /app/auth-service.jar

ENTRYPOINT ["java", "-Dspring.profiles.active=${SPRING_PROFILE}","-jar", "auth-service.jar"]